package com.mobile.unifyhealth.model

enum class HealthDataType {
    // Activity
    STEPS, DISTANCE, FLOORS_CLIMBED, ACTIVE_ENERGY_BURNED, BASAL_ENERGY_BURNED, MOVE_MINUTES, EXERCISE,

    // Body Measurements
    WEIGHT, HEIGHT, BODY_FAT_PERCENTAGE, LEAN_BODY_MASS, BODY_MASS_INDEX, BODY_TEMPERATURE,

    // Vitals
    HEART_RATE, HEART_RATE_VARIABILITY, BLOOD_PRESSURE, BLOOD_GLUCOSE, OXYGEN_SATURATION, RESPIRATORY_RATE, VO2_MAX,

    // Sleep & Nutrition
    SLEEP, WATER, NUTRITION,

    // Cycle Tracking
    MENSTRUATION, OVULATION_TEST, CERVICAL_MUCUS, SEXUAL_ACTIVITY, INTERMENSTRUAL_BLEEDING
}